version: '3.8'

services:
  astrbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astrbot
    restart: unless-stopped
    ports:
      - "6185:6185"
      - "6186:6186"
    volumes:
      - ./python:/AstrBot
      - ./c:/app/c
    environment:
      - TZ=Asia/Shanghai
    networks:
      - astrbot-network

networks:
  astrbot-network:
    driver: bridge